spring:
  datasource:
    url: <JDBC_URL>
    username: <JDBC_USERNAME>
    password: <JDBC_PASSWORD>
    driver-class-name: <DRIVER_CLASS_NAME>

encryption:
  key: <KEY>

api:
  #한국천문연구원
  kasi:
    key: <KEY>