language: java
jdk:
- openjdk11
  
branches:
  only:
  - master
    
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.gradle
    
before_script:
- chmod +x gradlew
  
script:
- ./gradlew clean build
  
after_success:
- ./gradlew jacocoTestReport coveralls
  
notifications:
  slack:
    secure: ZqRr4tui5/uEa630ANO7PKFYCSkE0mdwLR3At32+MB1FmWG5djSO7iDUXBf1sLacQgVJIBHuzKG63OdkJ4phkErTzArAY5WK7dIg5+GZ8M4PDWpS6h/JCEishvJSHHkEWHtU0G05rccIN+XvDGTakdaLP17XJgAWq9m2UJSlEbkfZ2ugT+qO19HnD76haisG6d/r7C3PLbjzQqmMG4UtYotMwdgikjJDKX7F1J+k8+s5gAb/B+HbpmTc8E/33wpDOpeyqZUfE3+2B0oFwwD31ZAd/oSe4yN+5ENaMsp5xGuGnoBkj94yGwaHB8GIAW1vxcKmuiJ+0sOeympvshjlHdyt5a/pkZM3Paips1YMsKDSBveyFQgEtpJO+30vY82ox8BI8TTxJnrOPr7D8xBIk6C7hJHddlvcKpmGrFefz+nsPhg6xhXM0jqTExgvbPoLsUxUctN3FiYU/d9Vl/72YvRzYY0OlpwfUa+QvDAAgV5/qde6uMhqXKMRHbzyDW6Q58sCnGGNQGtylJxKTQOLMZ3Yn5meTWC0Ow7cTNjKehCYQ5GOqTUbFrQsv6mzw5R1TtlQjbn6mYzhin2QUrntkbeMcVbHQUPo7hpETE9Q/SCKLib5IJHK6Nm1HVGdGbxdJjQfsG94OhonR0YLJ2FXI+6CaXKQ/uabKoKXt/PpW/Y=
  email:
    recipients:
    - workerhub.official@gmail.com