spring:
  application:
    name: worker-hub-web
  config:
    activate:
      on-profile: local
    import: application-secret-local.yml

  datasource:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8000