version: '3'
services:
  worker-hub-db:
    platform: linux/x86_64
    image: library/mysql:8.0.23
    container_name: mysql-8.0.23
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
