spring:
  application:
    name: worker-hub-api
  config:
    activate:
      on-profile: local
    import: application-secret-local.yml

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm
    servlet:
      load-on-startup: 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /api